import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    (<html
      lang="en"
      component-id="cdb677f3-3c39-408e-9442-b819188e8803"
      testparty-id={crypto.randomUUID()}>
      {children}
    </html>)
  );
}
