import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body aria-hidden="false">
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
